### ISSUE TITLE
webrtc/RtStreaming

### ISSUE THREAD

**Issue by kathiravan-17** [WebRTSP/RtStreaming#1]
[ 10%] Built target CxxPtr

[ 20%] Building CXX object GstRtStreaming/CMakeFiles/GstRtStreaming.dir/GstClient.cpp.o

/home/kathiravan/webrtc/RtStreaming/GstRtStreaming/GstClient.cpp: In member function ‘virtual void GstClient::prepare()’:

/home/kathiravan/webrtc/RtStreaming/GstRtStreaming/GstClient.cpp:30:9: error: ‘GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY’ was not declared in this scope

   30 |         GST_WEBRTC_RTP_TRANSCEIVER_DIRECTION_RECVONLY, capsPtr.get(),

      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/home/kathiravan/webrtc/RtStreaming/GstRtStreaming/GstClient.cpp:31:10: error: ‘recvonlyTransceiver’ was not declared in this scope

   31 |         &recvonlyTransceiver);

      |          ^~~~~~~~~~~~~~~~~~~

/home/kathiravan/webrtc/RtStreaming/GstRtStreaming/GstClient.cpp:32:5: error: ‘GstWebRTCRTPTransceiverPtr’ was not declared in this scope

   32 |     GstWebRTCRTPTransceiverPtr recvonlyTransceiverPtr(nullptr);

      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~

make[2]: *** [GstRtStreaming/CMakeFiles/GstRtStreaming.dir/build.make:82: GstRtStreaming/CMakeFiles/GstRtStreaming.dir/GstClient.cpp.o] Error 1

make[1]: *** [CMakeFiles/Makefile2:191: GstRtStreaming/CMakeFiles/GstRtStreaming.dir/all] Error 2

make: *** [Makefile:103: all] Error 2

**Comment by kathiravan-17** [comment]
while bulding above isue is comming

**Comment by RSATom** [comment]
What GStreamer version do you use?

**Comment by kathiravan-17** [comment]
GStreamer 1.18.4

**Comment by RSATom** [comment]
Do you try build it as part of some other project?

**Comment by kathiravan-17** [comment]
no i am just building as its

**Comment by RSATom** [comment]
Ok, I'll check. Just never build it standalone so issues are possible.

**Comment by RSATom** [comment]
Tried to build it standalone on Ubuntu 20.10 (It's GStreamer v1.18.0 there) and didn't get any issues... Interesting... Maybe it's something was changed in includes in 1.18.4...

**Comment by RSATom** [comment]
@kathiravan-17 can you please try add
```
#include <gst/webrtc/webrtc_fwd.h>
```
after  https://github.com/WebRTSP/RtStreaming/blob/master/GstRtStreaming/GstClient.cpp#L7 and try build it again?

**Comment by kathiravan-17** [comment]
build got success and static lib generated

**Comment by RSATom** [comment]
fixed by https://github.com/WebRTSP/RtStreaming/commit/588b3c36dd07b6f494f24c74f76684caef464274
