### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by dxur** [WebRTSP/RtStreaming#2]

**Comment by RSATom** [comment]
Yes, I know. Right now it's better to look into apps sources (like https://github.com/WebRTSP/ClockServer or https://github.com/WebRTSP/ReStreamer or https://github.com/RSATom/JanusVideoroomStreamer)
Or if you have any specific question - you may ask.

**Comment by RSATom** [comment]
I decided it would be bad Idea to use this repo in any 3rd party project since API is absolutely not stable and can be changed very significantly. So documenting it has no any meaning right now....
